import { CycloneScenario } from '../shared/types.js';

export const HISTORICAL_SCENARIOS: CycloneScenario[] = [
  {
    id: 'amphan-2020',
    name: 'Super Cyclone Amphan (2020)',
    year: 2020,
    basin: 'Bay of Bengal',
    regionName: 'West Bengal & Sundarbans Delta',
    historicalNote: 'Approximate historical replay parameters. Made landfall on May 20, 2020 across the Sundarbans mangrove delta and South 24 Parganas with catastrophic storm surge and severe grid disruption.',
    isApproximateReplay: true,
    center: [22.0, 88.4],
    zoom: 9,
    track: [
      {
        lat: 16.5,
        lng: 86.8,
        timestamp: '2020-05-18T12:00:00Z',
        hoursToLandfall: 48,
        maxWindKmh: 240,
        centralPressureHpa: 910,
        category: 'Super Cyclonic Storm',
      },
      {
        lat: 18.2,
        lng: 87.2,
        timestamp: '2020-05-19T06:00:00Z',
        hoursToLandfall: 30,
        maxWindKmh: 215,
        centralPressureHpa: 925,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 19.8,
        lng: 87.7,
        timestamp: '2020-05-19T18:00:00Z',
        hoursToLandfall: 18,
        maxWindKmh: 195,
        centralPressureHpa: 935,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 21.0,
        lng: 88.1,
        timestamp: '2020-05-20T06:00:00Z',
        hoursToLandfall: 6,
        maxWindKmh: 175,
        centralPressureHpa: 948,
        category: 'Very Severe Cyclonic Storm',
      },
      {
        lat: 21.72,
        lng: 88.35,
        timestamp: '2020-05-20T12:30:00Z',
        hoursToLandfall: 0,
        maxWindKmh: 165,
        centralPressureHpa: 955,
        category: 'Very Severe Cyclonic Storm',
      },
      {
        lat: 22.5,
        lng: 88.45,
        timestamp: '2020-05-20T18:00:00Z',
        hoursToLandfall: -6,
        maxWindKmh: 120,
        centralPressureHpa: 975,
        category: 'Severe Cyclonic Storm',
      },
    ],
    landfall: {
      lat: 21.72,
      lng: 88.35,
      estimatedTime: '2020-05-20T12:30:00Z',
      tideLevelM: 1.5,
    },
    parameters: {
      maxSustainedWindKmh: 175,
      centralPressureHpa: 945,
      radiusMaxWindKm: 38,
      forwardSpeedKmh: 24,
      shelfSlope: 0.0012, // extremely shallow northern Bay of Bengal head
      inlandAttenuationMPerKm: 0.38,
      rainfall24hMm: 240,
      antecedentMoistureCondition: 'saturated',
    },
  },
  {
    id: 'fani-2019',
    name: 'Extremely Severe Cyclone Fani (2019)',
    year: 2019,
    basin: 'Bay of Bengal',
    regionName: 'Odisha Coastal Corridor (Puri - Paradip)',
    historicalNote: 'Approximate historical replay parameters. Made landfall on May 3, 2019 near Puri, Odisha, packing sustained winds of over 200 km/h with record wind damage to transmission towers and coastal forests.',
    isApproximateReplay: true,
    center: [20.0, 85.9],
    zoom: 9,
    track: [
      {
        lat: 14.5,
        lng: 84.8,
        timestamp: '2019-05-01T12:00:00Z',
        hoursToLandfall: 42,
        maxWindKmh: 215,
        centralPressureHpa: 932,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 16.8,
        lng: 85.1,
        timestamp: '2019-05-02T06:00:00Z',
        hoursToLandfall: 24,
        maxWindKmh: 210,
        centralPressureHpa: 935,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 18.5,
        lng: 85.4,
        timestamp: '2019-05-02T18:00:00Z',
        hoursToLandfall: 12,
        maxWindKmh: 205,
        centralPressureHpa: 938,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 19.81,
        lng: 85.83,
        timestamp: '2019-05-03T06:00:00Z',
        hoursToLandfall: 0,
        maxWindKmh: 195,
        centralPressureHpa: 944,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 20.35,
        lng: 86.2,
        timestamp: '2019-05-03T12:00:00Z',
        hoursToLandfall: -6,
        maxWindKmh: 145,
        centralPressureHpa: 965,
        category: 'Very Severe Cyclonic Storm',
      },
    ],
    landfall: {
      lat: 19.81,
      lng: 85.83,
      estimatedTime: '2019-05-03T06:00:00Z',
      tideLevelM: 0.9,
    },
    parameters: {
      maxSustainedWindKmh: 205,
      centralPressureHpa: 936,
      radiusMaxWindKm: 32,
      forwardSpeedKmh: 18,
      shelfSlope: 0.0022,
      inlandAttenuationMPerKm: 0.42,
      rainfall24hMm: 190,
      antecedentMoistureCondition: 'moderate',
    },
  },
  {
    id: 'michaung-2023',
    name: 'Severe Cyclonic Storm Michaung (2023)',
    year: 2023,
    basin: 'Bay of Bengal',
    regionName: 'Andhra Pradesh & North Tamil Nadu',
    historicalNote: 'Approximate historical replay parameters. Characterized by unprecedented slow motion near Chennai resulting in extreme rainfall runoff (>400 mm), followed by landfall in Bapatla, Andhra Pradesh.',
    isApproximateReplay: true,
    center: [14.0, 80.2],
    zoom: 8,
    track: [
      {
        lat: 12.8,
        lng: 80.6,
        timestamp: '2023-12-03T12:00:00Z',
        hoursToLandfall: 36,
        maxWindKmh: 95,
        centralPressureHpa: 990,
        category: 'Cyclonic Storm',
      },
      {
        lat: 13.5,
        lng: 80.4,
        timestamp: '2023-12-04T06:00:00Z',
        hoursToLandfall: 20,
        maxWindKmh: 110,
        centralPressureHpa: 984,
        category: 'Severe Cyclonic Storm',
      },
      {
        lat: 14.8,
        lng: 80.2,
        timestamp: '2023-12-05T08:00:00Z',
        hoursToLandfall: 0,
        maxWindKmh: 105,
        centralPressureHpa: 986,
        category: 'Severe Cyclonic Storm',
      },
    ],
    landfall: {
      lat: 14.8,
      lng: 80.2,
      estimatedTime: '2023-12-05T08:00:00Z',
      tideLevelM: 0.8,
    },
    parameters: {
      maxSustainedWindKmh: 110,
      centralPressureHpa: 984,
      radiusMaxWindKm: 45,
      forwardSpeedKmh: 12,
      shelfSlope: 0.002,
      inlandAttenuationMPerKm: 0.35,
      rainfall24hMm: 380, // record precipitation
      antecedentMoistureCondition: 'saturated',
    },
  },
  {
    id: 'mocha-2023',
    name: 'Extremely Severe Cyclone Mocha (2023)',
    year: 2023,
    basin: 'Bay of Bengal',
    regionName: 'Myanmar (Rakhine) & Cox\'s Bazar',
    historicalNote: 'Approximate historical replay parameters. Made landfall on May 14, 2023 near Sittwe, Myanmar, driving a devastating 3.5m storm surge into low-lying coastal estuaries and humanitarian refugee settlements.',
    isApproximateReplay: true,
    center: [20.5, 92.8],
    zoom: 8,
    track: [
      {
        lat: 17.5,
        lng: 90.5,
        timestamp: '2023-05-13T06:00:00Z',
        hoursToLandfall: 28,
        maxWindKmh: 220,
        centralPressureHpa: 930,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 19.2,
        lng: 91.8,
        timestamp: '2023-05-13T20:00:00Z',
        hoursToLandfall: 14,
        maxWindKmh: 210,
        centralPressureHpa: 935,
        category: 'Extremely Severe Cyclonic Storm',
      },
      {
        lat: 20.2,
        lng: 92.85,
        timestamp: '2023-05-14T10:00:00Z',
        hoursToLandfall: 0,
        maxWindKmh: 195,
        centralPressureHpa: 942,
        category: 'Extremely Severe Cyclonic Storm',
      },
    ],
    landfall: {
      lat: 20.2,
      lng: 92.85,
      estimatedTime: '2023-05-14T10:00:00Z',
      tideLevelM: 1.8,
    },
    parameters: {
      maxSustainedWindKmh: 210,
      centralPressureHpa: 935,
      radiusMaxWindKm: 34,
      forwardSpeedKmh: 26,
      shelfSlope: 0.0016,
      inlandAttenuationMPerKm: 0.45,
      rainfall24hMm: 210,
      antecedentMoistureCondition: 'moderate',
    },
  },
];
